### ISSUE TITLE
 Missing `javascript` Module on WSL2

### ISSUE THREAD

**Issue by DoloMike** [mc-bench/orchestrator#10]
### Issue: Missing `javascript` Module on WSL2

**Summary**:  
When running the orchestrator on WSL2, the `build_structure` task fails with the error:  `No module named 'javascript'`.

The error occurs because `mineflayer.py` contains the import:  
  ```python
  from javascript import require, On, Once, AsyncTask, once, off
```

**Steps to Reproduce**

1. Set up the orchestrator on WSL2 according to the README.
2. Run `python test.py`.
3. Observe the error in the logs

**Temporary Workaround**

Install the `javascript` Python module with:

```bash
pip install javascript
```

**Unclear Dependencies**
It is uncertain if nodejs/npm are required or if installing only the javascript Python module is sufficient.

**Proposed Fix**
- Add the `javascript` package to `requirements.txt.`
- Clarify in the README **_if_** nodejs and npm are required dependencies.

**Comment by nikshepsvn** [comment]
yes, this should be in the requirements.txt, fixed
